title: Large Language Models for Knowledge Graph and Ontology Engineering
logo: assets/images/llm-kg-logo.png
description: 2024 AAAI Fall Symposium for Large Language Models for Knowledge Graph and Ontology Engineering
show_downloads: false

remote_theme: pages-themes/minimal@v0.2.0
plugins:
    - jekyll-remote-theme
